In [1]:
import numpy as np

In [2]:
a=np.arange(15)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a=a.reshape(3,5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# ndim returns the number of axis of numpy array

a.ndim

2

In [7]:
# reurns the type of the elements present inside the numpy ndArray
a.dtype.name


'int32'

In [8]:
# size returns number of elements in numpy array
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b=np.array([6,7,8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [13]:
# Array Creation in numpy , we can specify dtype during compilation

b =  np.array([ [1,2] , [3,4] ] , dtype=complex)



In [14]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
# Function zeros () contains an array full of zero

np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
# Function ones() creates an array full of ones

np.ones( (2,2,3) , dtype =np.int16 )

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [18]:
#To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [20]:
np.arange(0,50,10)

array([ 0, 10, 20, 30, 40])

In [21]:
# arrange (start,stop,steps)

In [23]:
from numpy import pi

In [24]:
x = np.linspace( 0, 2*pi, 100 )

In [25]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [26]:
# when numbers are floating numbers it is recommended to use linspace

In [27]:
# instead of using steps

In [30]:
# Create 1 d array

a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [34]:
# Create 2 d array

b=np.arange(12).reshape(4,3)

print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
# Create 3d array

c= np.arange(24).reshape(4,3,2)

print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [37]:
# Arithmetic operators on arrays apply elementwise. 
# A new array is created and filled with the result.

In [40]:
a=np.array([20,30,40])
b=np.arange(3)
c=a-b
c

array([20, 29, 38])

In [42]:
a**2

array([ 400,  900, 1600], dtype=int32)

In [43]:
2*a

array([40, 60, 80])

In [45]:
# Unlike in many matrix languages, 
# the product operator * operates elementwise in NumPy arrays. 
# The matrix product can be performed using the @ operator (in python >=3.5)
# or the dot function or method:

A = np.array([
                [1,1] ,
                [0,1]
            ])
B = np.array([
                [2,0] ,
                [3,4]
            ])


In [46]:
# Element wise multiplication in numpy using * operator

A*B

array([[2, 0],
       [0, 4]])

In [48]:
# Matrix product using @ opertor

A@B

array([[5, 4],
       [3, 4]])

In [51]:
# Matrix product using dot function

A.dot(B)

array([[5, 4],
       [3, 4]])